services:
  backend:
    image: subhomoy/llm-gateway-backend:dev-latest
    container_name: llm-gateway-backend-og
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    entrypoint: [ "./entrypoint.sh" ]
    volumes:
      - static_volume:/usr/src/main/static
      - media_volume:/usr/src/main/media
    env_file:
      - prod.env
    expose:
      - 8000
    environment:
      - DEBUG=1
      - MODE=server
      - PORT=8000
      - DATABASE=postgres
      - SECRET_KEY=v6nvsn^*dh5d839)^dp1y2s+3q06o&u^4hm@3msf)50s+^t@1p
    networks:
      - nginx_network

  nginx:
    image: nginx:alpine
    ports:
      - 8000:8000
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - static_volume:/usr/src/main/static
      - media_volume:/usr/src/main/media
    depends_on:
      - backend
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
