version: '3.8'

services:
  backend:
    image: subhomoy/llm-gateway-backend:latest
    container_name: llm-gateway-backend-og
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8001:8000
    env_file:
      - .env
    environment:
      - MODE=server
      - PORT=8000