# Generated by Django 5.1.2 on 2024-11-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_authuser_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='lastname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
