# Generated by Django 5.1.2 on 2024-11-01 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0005_alter_authuser_lastname_alter_authuser_username'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='authuser',
            name='lastname_valid',
        ),
        migrations.AlterField(
            model_name='authuser',
            name='lastname',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Lastname must contain only letters and spaces', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AddConstraint(
            model_name='authuser',
            constraint=models.CheckConstraint(condition=models.Q(('lastname__iregex', '^[a-zA-Z\\s]+$')), name='lastname_valid'),
        ),
    ]
