# Generated by Django 5.1.2 on 2024-11-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_authuser_lastname_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='name',
            field=models.CharField(default='Default', max_length=128),
        ),
    ]
