# Generated by Django 5.1.3 on 2024-12-02 05:59

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for the app', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the application', max_length=255)),
                ('feature_type', models.CharField(choices=[('webui', 'Web UI'), ('sdk', 'SDK')], help_text='Type of the feature configuration', max_length=50)),
                ('config', models.JSONField(default=dict, help_text='JSON configuration for the feature (e.g., theme, API limits)')),
                ('supported_models', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="List of supported models (e.g., ['GPT-3.5', 'GPT-4'])", size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_provider', models.CharField(default='email', max_length=20)),
                ('email', models.EmailField(help_text='Autogenerated email for the app user', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Encrypted password for the app user', max_length=128)),
                ('first_name', models.CharField(help_text='First name of the app user', max_length=50)),
                ('last_name', models.CharField(help_text='Last name of the app user', max_length=50)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_users', to='ai_apps.apps')),
            ],
            options={
                'unique_together': {('app', 'email')},
            },
        ),
    ]
