from django.db import models

# Create your models here.
    
class LLM_Model(models.Model):
    name = ...
    description = ...
    configuration = ...
    provider = ... #Enum
    developer = ...
    model_name = ...

# class User_API_Key(models.Model):
#     customer = ...
#     provider = ...
#     api_key = ...