name: Docker Build and Push

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: subhomoy/llm-gateway-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Set Dockerfile and tags based on branch
        id: docker-config
        run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            echo "dockerfile=Dockerfile" >> $GITHUB_ENV
            echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$GITHUB_ENV_TIMESTAMP" >> $GITHUB_ENV
          else
            echo "dockerfile=Dockerfile" >> $GITHUB_ENV
            echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-$GITHUB_ENV_TIMESTAMP" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.dockerfile }}
          push: true
          tags: ${{ env.tags }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Print image details
        run: |
          echo "Built and pushed images:"
          echo "Dockerfile: ${{ env.dockerfile }}"
          echo "Tags: ${{ env.tags }}"
